version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - BEACON_NODE_URL=${BEACON_NODE_URL:-http://localhost:5052/}
      - EXECUTION_NODE_URL=${EXECUTION_NODE_URL:-http://localhost:8545/}
      - X_API_KEY=${X_API_KEY:-}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # We've updated the backend Dockerfile to use these env variables

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:5000}
    depends_on:
      - backend 